export * from './header/header.tsx';
export * from './footer/footer.tsx';
export * from './error-message/error-message.tsx';
export * from './show-more/show-more.tsx';
export * from './genres-list/genres-list.tsx';
export * from './movies-list/movies-list.tsx';
export * from './loader/loader.tsx';
export * from './movie-page-tabs/movie-page-tabs.tsx';
export * from './add-review-form/add-review-form.tsx';
